require: 
  - rubocop-rails 
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
 Exclude:
 - db/schema.rb
 - db/migrate/**/*
 - lib/tasks/**/*
 - node_modules/**/*
 - bin/**/*

Metrics/LineLength:
  Max: 120

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: normal, indented_internal_methods

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowInHeredoc.
Layout/TrailingWhitespace:
  Exclude:
    - 'config/environments/test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

# Offense count: 10
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/railway_stations_controller.rb'
    - 'app/controllers/trains_controller.rb'
    - 'app/controllers/welcome_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/railway_stations_helper.rb'
    - 'app/helpers/trains_helper.rb'
    - 'app/helpers/welcome_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/railway_stations_controller.rb'
    - 'app/controllers/trains_controller.rb'
    - 'app/controllers/welcome_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

# Offense count: 29
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'app/views/railway_stations/index.json.jbuilder'
    - 'app/views/railway_stations/show.json.jbuilder'
    - 'app/views/trains/index.json.jbuilder'
    - 'app/views/trains/show.json.jbuilder'
    - 'config/application.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'spec/rails_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'test/channels/application_cable/connection_test.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets
